services:
  nginx:
    image: nginx:1-alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf.template:/etc/nginx/templates/default.conf.template"
    environment:
      APP_HOST: $APP_HOST
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost/ping"]

  app1:
    image: $IMAGE1
    restart: unless-stopped
    env_file:
      - app1.env

  app2:
    image: $IMAGE2
    restart: unless-stopped
    env_file:
      - app2.env
